### PR TITLE
Add icons for LSL

### PR DESCRIPTION
**Pull request by buildersbrewery**
Linden Scripting Language of Second Life

https://wiki.secondlife.com/wiki/LSL_Portal

### CODE REVIEW

**Comment by buildersbrewery** [comment]
* [`./prefs/icon_lsl.tmPreferences`](https://github.com/Briles/gruvbox/blob/master/prefs/icon_lsl.tmPreferences) already exists, that's why I didn't add it.

**Comment by Briles** [comment]
It's only necessary to include a `2x` sized icon (without the 2x suffix) as the default because Sublime Text will scale it down.

This icon was originally part of the theme but I had replaced it with a more [generic solution](https://github.com/Briles/gruvbox/blob/master/icons/file_type_lsl.png) because I wasn't happy with the quality/colors of the icon & I didn't know much about LSL.

Correct me if I'm wrong but this icon doesn't seem to be specific to LSL and is more of a general script icon. Do you think it would be more recognizable to have the Second Life hand logo as the icon?

I'd like to come up with an icon that

1. Is easily recognizable
2. Works with all gruvbox variations
3. Fits the gruvbox style

The current offering doesn't fit these parameters:
lsl-icon

With the Second Life hand logo:
lsl-hand

**Comment by buildersbrewery** [comment]
* The one provided is the icon used in the viewer for inventory items of type `script`.
* Using the official Second Life logo might have legal issues, not sure that's a good idea.

/cc @lindenlab feedback?

**Comment by Briles** [comment]
I converted the script icon to gruvbox style. It may see some future tweaks.

untitled-1

**Pull request closed without merging**
