### PR TITLE
Redo #26

### LINKED ISSUE #21: Remove adding UUIDs to schemes as ST ignores them
`package.json`

```diff
@@ -22,8 +22,7 @@
     "mocha": "^3.0.1",
     "plist": "^1.2.0",
     "run-sequence": "^1.2.2",
-    "tinycolor2": "^1.4.1",
-    "uuid": "^2.0.2"
+    "tinycolor2": "^1.4.1"
   },
   "scripts": {
     "style": "npm run style:main",
```

`src/scheme.js`

```diff
@@ -1,8 +1,6 @@
 module.exports = function (values) {
   'use strict';
 
-  const uuid = require('uuid');
-
   const c = values.colors;
   const info = values.info;
 
@@ -1525,6 +1523,5 @@ module.exports = function (values) {
       },
 
     ],
-    uuid: uuid.v4(),
   };
 };
```

### PR DESCRIPTION
**Pull request by jrappen**
* THEMES
  * fixed Briles/gruvbox#24
  * added support for the Skins package
* COLOR SCHEMES
  * added support for the Skins package
* Support
  * open README, CHANGELOG or CONTRIBUTING as md2html phantom via mdpopups
  * report issues via menu or control palette
* Development
  * removed unused 'uuid' npm dependency (fix #21 because Briles/gruvbox@fa29125)
  * moved 'scr' to '.gulp' and updated references
  * moved icon preferences output from 'prefs' to 'metadata' as those are TextMate metadata files

---

Already re-built and prepared for version `2.4.0`. You'll need to:

* merge develop into master
* tag the commit
* release on Github

on your own.

---

If you have a question, just ask.

### CODE REVIEW

**Comment by jrappen** [comment]
@Briles No changes regarding st-file-icons, as there are too many changes now right before the new major version there. I'd suggest waiting a while before targetting that.

**Comment by jrappen** [comment]
@Briles I just discovered that Github supports collapsible content in Markdown files via the HTML5 element `<details>`. See <https://forum.sublimetext.com/t/make-better-readmes-on-github/25842>. Should I wrap some parts of the README before merge or will you do that later?

**Comment by jrappen** [comment]
The README entry in the command palette and the main menu now opens the project page on Github in the default browser as images were not shown via mdpopups and the first collapsible section broke the phantom from that point on.

As the CHANGELOG and CONTRIBUTING files only have text, I'm still showing them from local via mdpopups. For that reason, one could also remove the dependencies and just load the resource with markdown scope applied.

**Comment by jrappen** [comment]
@Briles Did you need anything changed before merging this?

**Comment by Briles** [comment]
@jrappen Thanks for these improvements!

**Pull request merged**
