### PR TITLE
Add support for the Skins package, update icons and move gulp src folder

### LINKED ISSUE #14: Can the file icons be enlarged?
Love this theme! Essentially can the icons on the left be enlarged just a tad?

screen shot 2016-06-28 at 12 06 14 pm

### PR DESCRIPTION
**Pull request by jrappen**
* add support for the Skins package by @deathaxe (Briles/gruvbox@939b91e)
* fix #14 (Briles/gruvbox@e85a41e)

---

As I'm not too familiar with `gulp`, I did not include the `*.svg` source files and the `*.svg` to `*.png` build process from [ihodev/sublime-file-icons](https://github.com/ihodev/sublime-file-icons).

### CODE REVIEW

**Comment by jrappen** [comment]
⚠️ needs rebuild due to Briles/gruvbox@03a4c6e

**Comment by jrappen** [comment]
@Briles As I'm not too familiar with `gulp`, I did not include the `*.svg` source files and the `*.svg` to `*.png` build process from [ihodev/sublime-file-icons](https://github.com/ihodev/sublime-file-icons).

**Comment by jrappen** [comment]
ping @Briles

**Comment by Briles** [comment]
My apologies for not reviewing this sooner. I'll try and find some time in the next few days to review your contributions. Thanks!

**Comment by jrappen** [comment]
Take your time, just pinged you as a reminder 👍

**Comment by Briles** [comment]
👍 for skins support
👍 for the minimap fix


In regards to the file icons support: 

Instead of overriding the Gruvbox file icons with the zz File Icons in the repo, it would be better to [add support](https://github.com/ihodev/sublime-file-icons#bring-support-of-the-file-icon-customization-to-your-theme) for the [zz File Icons](https://github.com/ihodev/sublime-file-icons) package and keep the original Gruvbox file icons. Those with the zz File Icons package installed will have the ability to override the icons if wanted.

**Comment by jrappen** [comment]
@Briles Ok, I'll redo this PR with the following changes only:

* moving gulp src files from `src` to `.gulp`
  * while updating references
  * while updating docs
  * while fixing test references
* add Skins package support
* fix #24
* rename icon `prefs` output folder to `metadata` as they are TextMate metadata files
* add st-file-icons support

What about the functionality of:

* update / installation / removal messages in status bar?
* opening the README and a CHANGELOG (merging the messages into one file should do?) via mdpopups in a phantom?

Compare [jrappen/sublime-wkhtmltopdf`/src/documentation.py`](https://github.com/jrappen/sublime-wkhtmltopdf/blob/master/src/documentation.py)

Let me know what you want and I'll re-open later today.

**Comment by Briles** [comment]
Sounds good! Feel free to add status bar messages & readme & changelog popups. If possible, I would like to give the readme & changelog their own commands & popups, instead of merging into a single file.

Thanks again!

**Comment by jrappen** [comment]
@Briles I wasn't going to merge the README and CHANGELOG. I meant to merge the files in the messages directory into the new CHANGELOG file. Will do it later today. Closing this for now.

**Pull request closed without merging**
